apiVersion: v1
kind: Namespace
metadata:
  name: e-commerce
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-db
---
apiVersion: v1
kind: Namespace
metadata:
  name: stage-db

---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
