version: "3.8"

services:
  user-service:
    build: ./user-service
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=ecommerce
      - JWT_SECRET=your_secret_key
    depends_on:
      - mysql
    ports:
      - "5001:5001"
    restart: always

  product-service:
    build: ./product-service
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=ecommerce
    depends_on:
      - mysql
    ports:
      - "5002:5002"
    restart: always

  order-service:
    build: ./order-service
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=ecommerce
      - JWT_SECRET=your_secret_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PRODUCT_SERVICE_URL=http://product-service:5002
    depends_on:
      - mysql
    ports:
      - "5003:5003"
    restart: always

  cart-service:
    build: ./cart-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_secret_key
      - PRODUCT_SERVICE_URL=http://product-service:5002
    depends_on:
      - redis
    ports:
      - "5004:5004"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - product-service
      - order-service
      - cart-service
    environment:
      - REACT_APP_USER_SERVICE_URL=http://localhost:5001
      - REACT_APP_PRODUCT_SERVICE_URL=http://localhost:5002
      - REACT_APP_ORDER_SERVICE_URL=http://localhost:5003
      - REACT_APP_CART_SERVICE_URL=http://localhost:5004

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - ./dumb.sql:/docker-entrypoint-initdb.d/dumb.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql-data:
