apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: frontend
build:
  artifacts:
    - image: your-docker-repo/frontend
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/frontend-deployment.yaml
      - k8s/frontend-service.yaml
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
          - k8s/frontend-deployment-dev.yaml
          - k8s/frontend-service-dev.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/frontend-deployment-prod.yaml
          - k8s/frontend-service-prod.yaml
