env_vars:
  REACT_APP_USER_SERVICE_URL:
    name: frontend-configmap
    key: REACT_APP_USER_SERVICE_URL
  REACT_APP_PRODUCT_SERVICE_URL:
    name: frontend-configmap
    key: REACT_APP_PRODUCT_SERVICE_URL
  REACT_APP_ORDER_SERVICE_URL:
    name: frontend-configmap
    key: REACT_APP_ORDER_SERVICE_URL
  REACT_APP_CART_SERVICE_URL:
    name: frontend-configmap
    key: REACT_APP_CART_SERVICE_URL

microservice:
  name: frontend
  namespace: e-commerce
  replicaCount: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  prePromotionAnalysis: frontend-healthcheck-pre
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository: j4ro123/e-commerce-frontend
    tag: latest
  containerPort: 3000
  service:
    type: ClusterIP
    port: 3000
