productionSlot: blue

env_vars:
  REACT_APP_USER_SERVICE_URL_BLUE: user-service-prod.e-commerce.svc.cluster.local:5001
  REACT_APP_USER_SERVICE_URL_GREEN: user-service-stage.e-commerce.svc.cluster.local:5001
  REACT_APP_PRODUCT_SERVICE_URL_BLUE: product-service-prod.e-commerce.svc.cluster.local:5002
  REACT_APP_PRODUCT_SERVICE_URL_GREEN: product-service-stage.e-commerce.svc.cluster.local:5002
  REACT_APP_ORDER_SERVICE_URL_BLUE: order-service-prod.e-commerce.svc.cluster.local:5003
  REACT_APP_ORDER_SERVICE_URL_GREEN: order-service-stage.e-commerce.svc.cluster.local:5003
  REACT_APP_CART_SERVICE_URL_BLUE: cart-service-prod.e-commerce.svc.cluster.local:5004
  REACT_APP_CART_SERVICE_URL_GREEN: cart-service-stage.e-commerce.svc.cluster.local:5004

microservice:
  name: frontend
  namespace: e-commerce
  replicaCount: 2
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository_blue: j4ro123/e-commerce-frontend
    repository_green: j4ro123/e-commerce-frontend
    tag_blue: latest
    tag_green: latest
  containerPort: 3000
  service:
    type: ClusterIP
    port: 3000
