productionSlot: blue

env_vars:
  DB_HOST_BLUE: mysql-prod.prod-db
  DB_HOST_GREEN: mysql-stage.stage-db
  DB_USER:
    secret: db-secret
    key: user
  DB_PASS:
    secret: db-secret
    key: password
  DB_NAME:
    secret: db-secret
    key: dbName
  JWT_SECRET:
    secret: jwt-secret
    key: secret
  REDIS_HOST_BLUE: redis-prod.prod-db
  REDIS_HOST_GREEN: redis-stage.stage-db
  REDIS_PORT:
    secret: redis-secret
    key: port
  REDIS_PASS:
    secret: redis-secret
    key: password
  PRODUCT_SERVICE_URL_BLUE: product-service-prod.e-commerce.svc.cluster.local:5002

microservice:
  name: order-service
  namespace: e-commerce
  replicaCount: 2
  current_environment_blue: prod
  current_environment_green: stage
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository_blue: j4ro123/e-commerce-order-service
    repository_green: j4ro123/e-commerce-order-service
    tag_blue: latest
    tag_green: latest
  containerPort: 5003
  service:
    type: ClusterIP
    port: 5003
