apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.microservice.name }}
  labels:
    app: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicaCount }}
  strategy:
    blueGreen:
      activeService: {{ .Values.microservice.name }}-prod
      previewService: {{ .Values.microservice.name }}-stage
      previewReplicaCount: 2
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Values.microservice.prePromotionAnalysis }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: "{{ .Values.microservice.image.repository }}:{{ .Values.microservice.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.microservice.resources.limits.cpu }}
              memory: {{ .Values.microservice.resources.limits.memory }}
            requests:
              cpu: {{ .Values.microservice.resources.requests.cpu }}
              memory: {{ .Values.microservice.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.microservice.containerPort }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env_vars.DB_HOST.name }}
                  key: {{ .Values.env_vars.DB_HOST.key }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.DB_USER.secret }}
                  key: {{ .Values.env_vars.DB_USER.key }}
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.DB_PASS.secret }}
                  key: {{ .Values.env_vars.DB_PASS.key }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.DB_NAME.secret }}
                  key: {{ .Values.env_vars.DB_NAME.key }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.JWT_SECRET.secret }}
                  key: {{ .Values.env_vars.JWT_SECRET.key }}
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env_vars.REDIS_HOST.name }}
                  key: {{ .Values.env_vars.REDIS_HOST.key }}
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.REDIS_PORT.secret }}
                  key: {{ .Values.env_vars.REDIS_PORT.key }}
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env_vars.REDIS_PASS.secret }}
                  key: {{ .Values.env_vars.REDIS_PASS.key }}
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env_vars.PRODUCT_SERVICE_URL.name }}
                  key: {{ .Values.env_vars.PRODUCT_SERVICE_URL.key }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds:
              {{ .Values.microservice.livenessProbe.initialDelaySeconds }}
            periodSeconds:
              {{ .Values.microservice.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds:
              {{ .Values.microservice.readinessProbe.initialDelaySeconds }}
