env_vars:
  DB_HOST:
    name: product-configmap
    key: DB_HOST
  DB_USER:
    secret: db-secret
    key: user
  DB_PASS:
    secret: db-secret
    key: password
  DB_NAME:
    secret: db-secret
    key: dbName

microservice:
  name: product-service
  namespace: e-commerce
  replicaCount: 2
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "200Mi"
      cpu: "100m"
  prePromotionAnalysis: product-healthcheck-pre
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository: j4ro123/e-commerce-product-service
    tag: latest
  containerPort: 5002
  service:
    type: ClusterIP
    port: 5002
