apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.microservice.name }}
  labels:
    app: {{ .Values.microservice.name }}
  namespace: {{ .Values.microservice.namespace }}
spec:
  replicas: {{ .Values.microservice.replicaCount }}
  strategy:
    blueGreen:
      activeService: {{ .Values.microservice.name }}-prod
      previewService: {{ .Values.microservice.name }}-stage
      previewReplicaCount: 2
      autoPromotionEnabled: true
      autoPromotionSeconds: 1
      prePromotionAnalysis:
        templates:
        - templateName: {{ .Values.microservice.prePromotionAnalysis }}
  selector:
    matchLabels:
      app: {{ .Values.microservice.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservice.name }}
    spec:
      containers:
        - name: {{ .Values.microservice.name }}
          image: "{{ .Values.microservice.image.repository }}:{{ .Values.microservice.image.tag }}"
          resources:
            limits:
              cpu: {{ .Values.microservice.resources.limits.cpu }}
              memory: {{ .Values.microservice.resources.limits.memory }}
            requests:
              cpu: {{ .Values.microservice.resources.requests.cpu }}
              memory: {{ .Values.microservice.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.microservice.containerPort }}
          env:
            - name: REACT_APP_USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env_vars.REACT_APP_USER_SERVICE_URL.name }}
                  key: {{ .Values.env_vars.REACT_APP_USER_SERVICE_URL.key }}
            - name: REACT_APP_PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name:
                    {{ .Values.env_vars.REACT_APP_PRODUCT_SERVICE_URL.name }}
                  key:
                    {{ .Values.env_vars.REACT_APP_PRODUCT_SERVICE_URL.key }}
            - name: REACT_APP_ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name:
                    {{ .Values.env_vars.REACT_APP_ORDER_SERVICE_URL.name }}
                  key: {{ .Values.env_vars.REACT_APP_ORDER_SERVICE_URL.key }}
            - name: REACT_APP_CART_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env_vars.REACT_APP_CART_SERVICE_URL.name }}
                  key: {{ .Values.env_vars.REACT_APP_CART_SERVICE_URL.key }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds:
              {{ .Values.microservice.livenessProbe.initialDelaySeconds }}
            periodSeconds:
              {{ .Values.microservice.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.microservice.containerPort }}
            initialDelaySeconds:
              {{ .Values.microservice.readinessProbe.initialDelaySeconds }}
