env_vars:
  DB_HOST:
    name: cart-configmap
    key: DB_HOST
  DB_USER:
    secret: db-secret
    key: user
  DB_PASS:
    secret: db-secret
    key: password
  DB_NAME:
    secret: db-secret
    key: dbName
  REDIS_HOST:
    name: cart-configmap
    key: REDIS_HOST
  REDIS_PORT:
    secret: redis-secret
    key: port
  REDIS_PASS:
    secret: redis-secret
    key: password
  JWT_SECRET:
    secret: jwt-secret
    key: secret
  PRODUCT_SERVICE_URL:
    name: order-configmap
    key: PRODUCT_SERVICE_URL

microservice:
  name: cart-service
  namespace: e-commerce
  replicaCount: 2
  resources:
    requests:
      memory: "64Mi"
      cpu: "250m"
    limits:
      memory: "128Mi"
      cpu: "500m"
  prePromotionAnalysis: cart-healthcheck-pre
  livenessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 15
  image:
    repository: j4ro123/e-commerce-cart-service
    tag: latest
  containerPort: 5004
  service:
    type: ClusterIP
    port: 5004
