apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: IngressContollerAndCertManDeploy
profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: ingress-nginx-controller
            remoteChart: ingress-nginx/ingress-nginx
            valuesFiles:
              - ./kubernetes/helm/ingress-nginx/values-dev.yaml
            namespace: ingress-nginx
          - name: cert-manager
            remoteChart: cert-manager/cert-manager
            valuesFiles:
              - ./kubernetes/helm/cert-manager/values.yaml
            namespace: cert-manager

  - name: prod
    deploy:
      helm:
        releases:
          - name: ingress-nginx-controller
            remoteChart: ingress-nginx/ingress-nginx
            valuesFiles:
              - ./kubernetes/helm/ingress-nginx/values.yaml
            namespace: ingress-nginx
          - name: cert-manager
            remoteChart: cert-manager/cert-manager
            valuesFiles:
              - ./kubernetes/helm/cert-manager/values.yaml
            namespace: cert-manager
